exports.toxinMasterList = [
  {
    id: '100',
    name: '1,4-dioxane ',
    descriptionId: 0,
    productType: 'skincare',
  },
  {
    id: '101-0',
    name: '2-Bromo-2-Nitropropane-1',
    descriptionId: 1,
    productType: 'skincare',
  },
  {
    id: '101-1',
    name: '3-Diol (Bromopol)',
    descriptionId: 1,
    productType: 'skincare',
  },
  {
    id: '102-0',
    name: 'Aluminum Hydroxide',
    descriptionId: 2,
    productType: 'skincare',
  },
  { id: '102-1', name: 'CI 77002', descriptionId: 2, productType: 'skincare' },
  {
    id: '103-0',
    name: 'Animal Fats',
    descriptionId: 3,
    productType: 'skincare',
  },
  { id: '103-1', name: 'Oils', descriptionId: 3, productType: 'skincare' },
  { id: '103-2', name: 'Musks', descriptionId: 3, productType: 'skincare' },
  {
    id: '104-0',
    name: 'Benzalkonium Chloride',
    descriptionId: 4,
    productType: 'skincare',
  },
  {
    id: '104-1',
    name: 'Alkyldimethylbenzylammonium chloride',
    descriptionId: 4,
    productType: 'skincare',
  },
  {
    id: '105-0',
    name: 'Benzophenones',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-1',
    name: 'Benzophenone-1',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-2',
    name: 'Benzophenone-2',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-3',
    name: 'Benzophenone-3',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-4',
    name: 'Oxybenzone',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-5',
    name: 'Benzophenone-4',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-6',
    name: 'Benzophenone-5',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-7',
    name: 'Benzophenone-6',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-8',
    name: 'Benzophenone-8',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-9',
    name: 'Benzophenone-9',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-10',
    name: 'Benzophenone-11',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '105-11',
    name: 'Benzophenone-12',
    descriptionId: 5,
    productType: 'skincare',
  },
  {
    id: '106',
    name: 'Benzylparaben',
    descriptionId: 6,
    productType: 'skincare',
  },
  {
    id: '107',
    name: 'BHA (Butylated Hydroxyanisole)',
    descriptionId: 7,
    productType: 'skincare',
  },
  {
    id: '108',
    name: 'BHT (Butylated Hydroxytoluene)',
    descriptionId: 8,
    productType: 'skincare',
  },
  {
    id: '109',
    name: 'Bismuth Oxychloride',
    descriptionId: 9,
    productType: 'skincare',
  },
  {
    id: '110',
    name: 'Bisphenol A (BPA)',
    descriptionId: 10,
    productType: 'skincare',
  },
  { id: '111-0', name: 'Borax', descriptionId: 11, productType: 'skincare' },
  {
    id: '111-1',
    name: 'Boric Acid',
    descriptionId: 11,
    productType: 'skincare',
  },
  {
    id: '111-2',
    name: 'Sodium Borate',
    descriptionId: 11,
    productType: 'skincare',
  },
  {
    id: '111-3',
    name: 'Sodium Tetraborate',
    descriptionId: 11,
    productType: 'skincare',
  },
  {
    id: '111-4',
    name: 'Disodium Tetraborate',
    descriptionId: 11,
    productType: 'skincare',
  },
  {
    id: '112-0',
    name: 'Boric Acid',
    descriptionId: 12,
    productType: 'skincare',
  },
  { id: '112-1', name: 'Borax', descriptionId: 12, productType: 'skincare' },
  {
    id: '112-2',
    name: 'Sodium Borate',
    descriptionId: 12,
    productType: 'skincare',
  },
  {
    id: '112-3',
    name: 'Sodium Tetraborate',
    descriptionId: 12,
    productType: 'skincare',
  },
  {
    id: '112-4',
    name: 'Disodium Tetraborate',
    descriptionId: 12,
    productType: 'skincare',
  },
  {
    id: '113-0',
    name: 'Butoxyethanol',
    descriptionId: 13,
    productType: 'skincare',
  },
  {
    id: '113-1',
    name: '2-Butoxyethanol',
    descriptionId: 13,
    productType: 'skincare',
  },
  {
    id: '114',
    name: 'Butylparaben',
    descriptionId: 14,
    productType: 'skincare',
  },
  {
    id: '115-0',
    name: 'Carbon Black',
    descriptionId: 15,
    productType: 'skincare',
  },
  { id: '115-1', name: 'CI 77266', descriptionId: 15, productType: 'skincare' },
  { id: '115-2', name: 'Black 2', descriptionId: 15, productType: 'skincare' },
  {
    id: '115-3',
    name: 'D&C Black No. 2',
    descriptionId: 15,
    productType: 'skincare',
  },
  {
    id: '115-4',
    name: 'acetylene black',
    descriptionId: 15,
    productType: 'skincare',
  },
  {
    id: '115-5',
    name: 'channel black furnace black',
    descriptionId: 15,
    productType: 'skincare',
  },
  {
    id: '115-6',
    name: 'lamp black',
    descriptionId: 15,
    productType: 'skincare',
  },
  {
    id: '115-7',
    name: 'thermal black',
    descriptionId: 15,
    productType: 'skincare',
  },
  { id: '116', name: 'Coal Tar', descriptionId: 16, productType: 'skincare' },
  {
    id: '117',
    name: 'Diazolidinyl Urea',
    descriptionId: 17,
    productType: 'skincare',
  },
  {
    id: '118-0',
    name: 'Diethyl Phthalate',
    descriptionId: 18,
    productType: 'skincare',
  },
  { id: '118-1', name: 'DEP', descriptionId: 18, productType: 'skincare' },
  {
    id: '119',
    name: 'DMDM Hydantoin',
    descriptionId: 19,
    productType: 'skincare',
  },
  {
    id: '120-0',
    name: 'Ethanolamine Compounds',
    descriptionId: 20,
    productType: 'skincare',
  },
  {
    id: '120-1',
    name: 'MEA/DEA/TEA',
    descriptionId: 20,
    productType: 'skincare',
  },
  {
    id: '121',
    name: 'Ethoxylated Ingredients',
    descriptionId: 21,
    productType: 'skincare',
  },
  {
    id: '122-0',
    name: 'Ethylenediaminetetraacetic Acid (EDTA)',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '122-1',
    name: 'Calcium Disodium EDTA',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '122-2',
    name: 'Diammonium EDTA',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '122-3',
    name: 'Dipotassium EDTA',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '122-4',
    name: 'Disodium EDTA',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '122-5',
    name: 'Tetrasodium EDTA',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '122-6',
    name: 'Tripotassium EDTA',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '122-7',
    name: 'Trisodium EDTA',
    descriptionId: 22,
    productType: 'skincare',
  },
  {
    id: '123',
    name: 'Ethylparaben',
    descriptionId: 23,
    productType: 'skincare',
  },
  {
    id: '124',
    name: 'Formaldehyde',
    descriptionId: 24,
    productType: 'skincare',
  },
  {
    id: '125-0',
    name: 'Formaldehyde-Releasing Preservatives',
    descriptionId: 25,
    productType: 'skincare',
  },
  {
    id: '125-1',
    name: 'DMDM Hydantoin',
    descriptionId: 25,
    productType: 'skincare',
  },
  {
    id: '125-2',
    name: 'Diazolidinyl Urea',
    descriptionId: 25,
    productType: 'skincare',
  },
  {
    id: '125-3',
    name: 'Imidazolidinyl Urea',
    descriptionId: 25,
    productType: 'skincare',
  },
  {
    id: '125-4',
    name: 'Quaternium-15',
    descriptionId: 25,
    productType: 'skincare',
  },
  {
    id: '125-5',
    name: '2-Bromo-2-Nitropropane-1',
    descriptionId: 25,
    productType: 'skincare',
  },
  { id: '125-6', name: '3-Diol', descriptionId: 25, productType: 'skincare' },
  {
    id: '125-7',
    name: 'Methenamine',
    descriptionId: 25,
    productType: 'skincare',
  },
  {
    id: '125-8',
    name: 'Sodium Hydroxymethylglycinate',
    descriptionId: 25,
    productType: 'skincare',
  },
  {
    id: '126-0',
    name: 'Grapefruit Seed Extract',
    descriptionId: 26,
    productType: 'skincare',
  },
  {
    id: '126-1',
    name: 'Citrus Paradisi (Grapefruit) Seed',
    descriptionId: 26,
    productType: 'skincare',
  },
  {
    id: '126-2',
    name: 'Citrus Grandis (Grapefruit) Seed Extract',
    descriptionId: 26,
    productType: 'skincare',
  },
  { id: '126-3', name: 'GSE', descriptionId: 26, productType: 'skincare' },
  {
    id: '127',
    name: 'Homosalate (HMS)',
    descriptionId: 27,
    productType: 'skincare',
  },
  {
    id: '128',
    name: 'Hydroquinone',
    descriptionId: 28,
    productType: 'skincare',
  },
  {
    id: '129',
    name: 'Imidazolidinyl Urea',
    descriptionId: 29,
    productType: 'skincare',
  },
  {
    id: '130',
    name: 'Iodopropynyl Butylcarbamate (IPBC)',
    descriptionId: 30,
    productType: 'skincare',
  },
  {
    id: '131',
    name: 'Isobutylparaben',
    descriptionId: 31,
    productType: 'skincare',
  },
  {
    id: '132',
    name: 'Isopropylparaben',
    descriptionId: 32,
    productType: 'skincare',
  },
  {
    id: '133',
    name: 'Japanese Honeysuckle Extract',
    descriptionId: 33,
    productType: 'skincare',
  },
  {
    id: '134',
    name: 'Loose Powder Titanium Dioxide',
    descriptionId: 34,
    productType: 'skincare',
  },
  {
    id: '135-0',
    name: 'Mercury & Mercury compounds',
    descriptionId: 35,
    productType: 'skincare',
  },
  {
    id: '135-1',
    name: 'Thimerosal',
    descriptionId: 35,
    productType: 'skincare',
  },
  {
    id: '136',
    name: 'Methenamine',
    descriptionId: 36,
    productType: 'skincare',
  },
  {
    id: '137',
    name: 'Methylchloroisothiazolinone/Methylisothiazolinone (MCI/MI)',
    descriptionId: 37,
    productType: 'skincare',
  },
  {
    id: '138',
    name: 'Methylparaben',
    descriptionId: 38,
    productType: 'skincare',
  },
  {
    id: '139',
    name: 'Mineral Oil',
    descriptionId: 39,
    productType: 'skincare',
  },
  {
    id: '140-0',
    name: 'Nanoparticles',
    descriptionId: 40,
    productType: 'skincare',
  },
  {
    id: '140-1',
    name: 'nanomaterials',
    descriptionId: 40,
    productType: 'skincare',
  },
  {
    id: '141-0',
    name: 'Octinoxate',
    descriptionId: 41,
    productType: 'skincare',
  },
  {
    id: '141-1',
    name: 'Octyl Methoxycinnamate',
    descriptionId: 41,
    productType: 'skincare',
  },
  {
    id: '141-2',
    name: 'Ethylhexyl Methoxycinnamate',
    descriptionId: 41,
    productType: 'skincare',
  },
  {
    id: '142-0',
    name: 'Oxybenzone',
    descriptionId: 42,
    productType: 'skincare',
  },
  {
    id: '142-1',
    name: 'Benzophenone-3',
    descriptionId: 42,
    productType: 'skincare',
  },
  { id: '143', name: 'Parabens', descriptionId: 43, productType: 'skincare' },
  {
    id: '144',
    name: 'PEGs (Polyethylene Glycol)',
    descriptionId: 44,
    productType: 'skincare',
  },
  {
    id: '145-0',
    name: 'Phenoxyethanol',
    descriptionId: 45,
    productType: 'skincare',
  },
  {
    id: '145-1',
    name: '2-phenoxyethanol',
    descriptionId: 45,
    productType: 'skincare',
  },
  { id: '146', name: 'Phthalates', descriptionId: 46, productType: 'skincare' },
  {
    id: '147',
    name: 'Propylene Glycol',
    descriptionId: 47,
    productType: 'skincare',
  },
  {
    id: '148',
    name: 'Propylparaben',
    descriptionId: 48,
    productType: 'skincare',
  },
  {
    id: '149',
    name: 'Quaternium-15',
    descriptionId: 49,
    productType: 'skincare',
  },
  { id: '150', name: 'Resorcinol', descriptionId: 50, productType: 'skincare' },
  {
    id: '151-0',
    name: 'Retinyl Palmitate/Retinol',
    descriptionId: 51,
    productType: 'skincare',
  },
  { id: '151-1', name: 'Retinoid', descriptionId: 51, productType: 'skincare' },
  {
    id: '151-2',
    name: 'Retinoic Acid',
    descriptionId: 51,
    productType: 'skincare',
  },
  {
    id: '152',
    name: 'Synthetic Flavors',
    descriptionId: 52,
    productType: 'skincare',
  },
  {
    id: '153',
    name: 'Synthetic Fragrances',
    descriptionId: 53,
    productType: 'skincare',
  },
  { id: '154-0', name: 'Talc', descriptionId: 54, productType: 'skincare' },
  {
    id: '154-1',
    name: 'Hydrous Magnesium Silicate',
    descriptionId: 54,
    productType: 'skincare',
  },
  {
    id: '155',
    name: 'Triclosan',
    descriptionId: 55,
    productType: 'skincare',
  },
  {
    id: '155-1',
    name: '5-Chloro-2',
    descriptionId: 55,
    productType: 'skincare',
  },
];
